### PR TITLE
WSL2 Support + README Update

### PR DESCRIPTION
**Pull request by thearchivalone**

### CODE REVIEW

**Comment by iromero91** [comment]
Interesting! could you tell me why you removed the wineprefix generation? it is there because it is needed to have a 32 bit prefix (which is not the default these days). the tools will not run properly on 64 bit wine.

**Comment by iromero91** [comment]
Also note that removing that breaks pm.mk on linux

**Comment by thearchivalone** [comment]
Honestly, the WINEPREFIX removal was more for the WSL2 side than anything else. WSL2 shows as Linux and WINE is meant to get apps to work on non Windows OS’s and would be redundant if using WSL2. I think it would be better to add instructions to the README under my Linux Specific section.

**Comment by bedwardly-down** [comment]
Added a 64-bit WINE Caveat with a link to the WINE FAQ page that explains the 32-bit issue you brought up and added a manual command for adding that WINEPREFIX back. Sorry about that. :D

**Comment by iromero91** [comment]
This still breaks on linux since pm.mk tries to use the now non-existent wineprefix. Is there a way to detect we are in WSL? (maybe using uname perhaps) I would like to make this patch less invasive and not break the existing straightforward linux functionality.

**Comment by thearchivalone** [comment]
So, WSL for all intents and purposes is a full Linux distro running on top of Windows with a custom kernel that hooks directly into the Windows kernel along with some hacks to get it running. Uname will show something like this if the user is not using their own custom kernel instead of the Microsoft one: `5.10.16.3-microsoft-standard-WSL2` . That's the only real difference, as far as I know. 

Current possible options:

1) User must install WINE on WSL along with X11 and any other normal dependencies. X11 works fine as long as you have an XServer application running on Windows and route it correctly (see here for one way to get that going: https://thomasward.com/wsl2-x11/).

2) My Makefile could be a separate one altogether that is specific to WSL2 users and has nothing to do with running it on Linux and then just drop a line in the README that directs the user to run the make command using it instead. This is probably the easiest option with how things currently are.

The core argument for replacing MSYS with WSL2 is how it directly integrates with Windows, is supported by Microsoft and has vastly more uses to the end user than MSYS due to its full Linux nature. It's also something that could be easier to get running for non tech people.

**Comment by thearchivalone** [comment]
I'm not sure if it's because of WSL2 or something else but the default Makefile requires two or three runs to get running properly (Wine cannot run 64-bit apps in 32-bit prefix bug). Also, you said the WINEPREFIX didn't exist. Did you make it using the extra instructions I added into the README under Wine 64 Caveat section? WINE installed fine for the most part otherwise.

**Comment by iromero91** [comment]
What about this: Use the uname or /proc/ or whatever method works most of the time. that will be enough for most casual users. Then add a variable to force that test to succeed for someone who knows what they are doing (they are installing custom kernels anyway right?). I don't have any feelings towards the removal of MSYS support. i guess at this point windows 10 is extended enough that i doubt anyone is really using msys2 anymore. In that case we can also remove the bin-windows target. For Linux support, please restore the previous function as is. Only implement a separate codepath for WSL on both the main makefile and pm.mk

**Comment by thearchivalone** [comment]
Thanks for getting back to me. I can check into that (will need to some studying since I don't mess with Makefiles enough; there are many better systems out there now, impo, but I digress)

**Comment by logicplace** [comment]
To throw a wrench into the discussion: I don't think installation needs to be a makefile to begin with. There isn't much, if any, benefit to making it one, and we can avoid this mess of conditionals by just having separate scripts for separate systems. We can have an install-wine.sh, install-wsl.sh, install-windows.ps1, and perhaps some sort of VM building script for Mac eventually.

Also I really think we should host the Epson tools somewhere else, since archive.org gets overloaded somewhat regularly. If Epson cared, they'd DMCA the archive.org link.

**Pull request closed without merging**
